name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0', '8.1' ]

    container: php:${{ matrix.php }}-cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        run: |
          apt update -yq
          apt install -yq golang libprotobuf-c-dev git zlib1g-dev valgrind

      - name: Cache bats-core
        id: cache-bats-core
        uses: actions/cache@v3
        with:
          key: bats-core-v2
          path: |
            /bats-core
            /bats-support
            /bats-assert
            /bats-file

      - if: ${{ steps.cache-bats-core.outputs.cache-hit == 'false' }}
        name: Setup bats-core
        run: |
          git clone https://github.com/bats-core/bats-core.git /bats-core
          git clone https://github.com/bats-core/bats-support.git /bats-support
          git clone https://github.com/bats-core/bats-assert.git /bats-assert
          git clone https://github.com/bats-core/bats-file.git /bats-file

      - name: Install bats-core
        run: |
          cd /bats-core && ./install.sh /usr/local && cd -

      - name: Build
        run: |
          phpize
          ./configure
          make && make install

      - name: Run tests
        run: make test TESTS="-q --show-diff"

      - name: Run functional tests
        run: bats tests
